version: '3.1'

networks:
  wiki-network:
    driver: bridge

services:
    db:
      build:
        dockerfile: ./postgres.dockerfile
        context: ./docker
      image: wiki-postgres-db
      container_name: wiki-db-container
      restart: always
      environment:
        POSTGRES_PASSWORD: admin
        POSTGRES_USER: admin
        POSTGRES_DB: wiki
      ports:
        - "5432:5432"
      networks:
        - wiki-network